'use strict';
const byId=id=>document.getElementById(id);
const escapeText=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const labels={auto_ready:'已入训练库',auto_reference:'仅供参考',quarantined:'未放行'};
let data={papers:[],warnings:[]},cards=[],selected='',filtered=[];
function prose(value){return String(value||'暂无说明').split(/(?<=[。！？])\s*/u).filter(Boolean).map(s=>`<p>${escapeText(s)}</p>`).join('');}
function safeLink(value){return /^(?:\/papers\/|file:\/\/\/)/.test(value||'')?value:'#';}
function renderList(){const paper=byId('paper').value,state=byId('state').value,q=byId('search').value.trim().toLowerCase();filtered=cards.filter(c=>(paper==='all'||c.paper_id===paper)&&(state==='all'||c.release_decision?.status===state)&&[c.claim,c.id,c.paper_title,c.release_decision?.reason].join(' ').toLowerCase().includes(q));if(!filtered.some(c=>c.id===selected))selected=filtered[0]?.id||'';byId('list').innerHTML=`<div class="counter">${filtered.length} 条结果</div>`+filtered.map(c=>`<button type="button" data-id="${escapeText(c.id)}" class="${c.id===selected?'active':''}" aria-pressed="${c.id===selected}"><span class="badge ${escapeText(c.release_decision?.status||'quarantined')}">${labels[c.release_decision?.status]||'未放行'}</span><strong>${escapeText(c.claim?.replace(/^隔离原因：/,'').slice(0,78)||'尚未形成结论')}${c.claim?.length>78?'…':''}</strong><small>${escapeText(c.id)}</small></button>`).join('');renderReader();}
function renderReader(){const c=filtered.find(c=>c.id===selected);if(!c){byId('reader').innerHTML='<p class="empty">没有符合条件的证据。换一个筛选条件即可。</p>';return;}const status=c.release_decision?.status||'quarantined';let notes='';try{notes=localStorage.getItem('ginger-review-note-'+c.id)||'';}catch{}const pages=[...new Set(c.page_numbers||[])];byId('reader').innerHTML=`<span class="badge ${escapeText(status)}">${labels[status]||'未放行'}</span><span class="id">${escapeText(c.id)}</span><h2>这条研究记录说了什么</h2><div class="conclusion">${prose(c.claim)}</div><h3>在哪里 怎样做的试验</h3>${prose(c.scope)}<h3>适用范围</h3>${prose(c.limitations)}<h3>${status==='quarantined'?'为什么没有放行':'核查结果'}</h3><div class="reason">${prose(c.release_decision?.reason)}</div><div class="paper-name">来源论文<br>${escapeText(c.paper_title)}</div><div class="links">${c.pdf_url?pages.map(p=>`<a href="${escapeText(safeLink(c.pdf_url).split('#')[0]+'#page='+p)}" target="_blank" rel="noreferrer">原文第 ${escapeText(p)} 页 ↗</a>`).join(''):''}<a href="${escapeText(safeLink(c.json_url))}" target="_blank" rel="noreferrer">完整证据记录 ↗</a></div><details><summary>需要核对时 查看原文片段</summary>${(c.evidence_anchors||[]).map(a=>`<p class="muted">PDF 第 ${escapeText(a.page)} 页</p><div class="excerpt">${escapeText(a.quote)}</div>`).join('')||'<p class="muted">本条没有可展示的原文锚点，请打开完整记录。</p>'}</details><details class="notes"><summary>记录自己的核对意见</summary><p class="muted">意见仅保存在这台设备的浏览器里，不改变证据放行状态。需要修订的事实仍应重新运行原文复核。</p><textarea id="note" aria-label="核对意见" placeholder="原文哪一页，哪一处需要修改？">${escapeText(notes)}</textarea><button type="button" id="save-note">保存意见到本机</button><span class="muted" id="note-result" role="status"></span></details><details><summary>开发字段与独立检查记录</summary><pre class="technical">${escapeText(JSON.stringify({source_pointers:c.source_pointers,independent_gate:c.independent_gate,numeric_comparisons:c.numeric_comparisons,statistical_checks:c.statistical_checks,currently_admitted:c.currently_admitted},null,2))}</pre></details>`;}
byId('list').addEventListener('click',e=>{const button=e.target.closest('button[data-id]');if(button){selected=button.dataset.id;renderList();}});
for(const id of ['paper','state','search'])byId(id).addEventListener(id==='search'?'input':'change',renderList);
byId('reader').addEventListener('click',e=>{if(e.target.id==='save-note'){try{localStorage.setItem('ginger-review-note-'+selected,byId('note').value);byId('note-result').textContent=' 已保存。';}catch{byId('note-result').textContent=' 浏览器未允许本机保存，请复制意见留存。';}}});
async function start(){try{data=location.protocol==='file:'?JSON.parse(byId('snapshot').textContent):await fetch('/api/debug/evidence',{cache:'no-store'}).then(r=>{if(!r.ok)throw Error('读取失败');return r.json();});cards=data.papers.flatMap(p=>p.cards.map(c=>({...c,paper_id:p.id,paper_title:p.title})));byId('paper').innerHTML='<option value="all">全部论文</option>'+data.papers.map(p=>`<option value="${escapeText(p.id)}">${escapeText(p.title)}</option>`).join('');const counts={auto_ready:0,auto_reference:0,quarantined:0};cards.forEach(c=>counts[c.release_decision?.status||'quarantined']++);byId('totals').textContent=`${data.papers.length} 篇论文 · ${cards.length} 条记录 · ${counts.auto_ready} 条入训练库 · ${counts.auto_reference} 条参考 · ${counts.quarantined} 条未放行`;byId('diagnostic-body').textContent=(data.warnings||[]).join('\n\n')||'没有资料接入诊断。';byId('mode').textContent=location.protocol==='file:'?'离线快照 · 实时结果请从姜小伴的开发调试入口打开。':'实时结果 · 每篇显示最近一次生成的记录。';renderList();}catch(e){byId('reader').innerHTML='<p class="empty">暂时没有读到记录。请先启动姜小伴，再从设置中的开发调试入口打开此页。</p>';}}
start();
